* Intro
"Welcome to the velvet room."

There is a world within every soul: a place made of thoughts and feelings,
carved by experience and used to hide things we don't want to reveal.
Normally, this place is kept quietly locked away behind a door whose key is
kept guarded by societal norms and cheerful facades. But, on occasion, and
with a little emotional leverage, the lock can be broken...

In Shin Origami Tensei, you play the role of one (or more) people known as
[Sinners]--people who allow their secrets to drive them. Almost all people
have a secret to keep, but most of them are able to maintain a semblance of
normal life, never allowing their secret to come to light. You aren't so
lucky. The secrets of a Sinner may be mundane or macabre, simple or
subliminal, a horrible crime or an inconvenience, but whatever it may be, it
is driving the Sinner to the limit of insanity. As you play SOT, your Sinner
will explore the world within their soul, and face their worst enemy: a
devious doppelganger that exists only to remind the Sinner of their own Sin.
If you can survive this battle, you will gain an incredible power. But if you
lose, you will be cursed to wander the earth alone.
* Player's Guide
** Character generation
Creating a Sinner is easy, and a Sinner's reference sheet can fit onto a
simple 3x5 index card with enough room for growth. To start with, each Sinner
has the following important figures:
- A name. SOT is built around a modern setting, but it is wise to talk to
  your GM before assuming.
- An [Elemental Affinity]. There are five elements: Fire, Ice, Lightning,
  Nature, and Physical. All characters can use Physical damage in their basic
  attack, but your special attacks often use your Affinity's damage type.
  Physical is not a recommended Affinity, but you can choose it; again, talk
  to your GM about it. He may offer some kind of advantage in exchange.
- An [Elemental Weakness]. Each character and Demon has a Weakness to one
  of the five elements. When struck by damage of the type it is weak to, a
  Demon will be stunned; similarly, a Sinner struck by damage they are weak
  to will be unable to act in their next turn.
- Two [Abilities]. An Ability can either be an [Active Ability] which
  requires Meter to use (see the Combat section) or a [Passive Ability] which
  requires that certain conditions be met. Work with your GM to create a set
  of Abilities that fit your play style and role.
- Three [Hit Points], a [Basic Attack] that deals 1 Physical damage, and the
  ability to [Guard] and reduce incoming damage. All characters are able to
  do this, and unless otherwise stated by a passive Ability or a Weapon (see
  the chapter on Progression), this is the limit of your character's base
  stats. Note that Abilities that increase your HP, boost your Basic Attack,
  or improve your Guard are very powerful, and your GM may not allow an
  ability that provides a flat boost to these stats. 
- If your GM allows it, one free Link Point. Link Points are discussed in 
  further detail in the chapter on Progression.
- A Social Rank of 1. Social Rank is detailed in the chapter on Progression.

You may want to coordinate with your party to create Abilities and choose
Affinities and Weaknesses. Although your characters may not know each other,
fate plays a strong role in stories such as these--and besides, you don't
want it to end in a massacre because nobody can heal a teammate, do you?
** Combat
Combat in SOT is "deterministic": an action will always lead to a certain
effect. For instance, a Basic Attack (assuming no Abilities or Weapons affect
it) will always deal 1 Physical damage to one target. An enemy that uses an
attack will always do exactly the same thing, assuming you aren't Guarding or
using an ability that affects incoming damage. Dice are not rolled, attacks
do not miss, and if you're not careful, you can cause yourself a world of
problems.
*** The Meter
The centerpiece of the fight is the [Soulfire Meter], often referred to as
the Meter. As you slay Demons or take advantage of their Weaknesses, you will
gain Meter, and you can 'tap' Meter to activate abilities. However, the Meter
is shared by the party; coordination and tactical decisions are key.
*** Verses, the Mainbeat, and the Backbeat
A battle consists of multiple "Verses", each one containing a wave of Demons.
Within each Verse, you will alternate between the 'Mainbeat', in which most
of your Sinner's actions will take place, and the 'Backbeat', in which one
or more Demons may attack. Some Demon abilities activate during the Mainbeat,
and some Sinner abilities may trigger in the Backbeat.
*** Your Action
On the Mainbeat, Sinners may act in any order. It is recommended that you
discuss among yourselves to choose a turn order, as it can be important.
When your Sinner acts, he or she may:
- Perform a Basic Attack. Unless modified by a Weapon or Ability, it deals 1
  Physical damage to 1 target.
- Use an Ability. This may require you to 'tap' a certain amount of Meter.
  The party as a whole may only tap an amount of Meter up to the Meter's
  current maximum each turn; however, the Meter is replenished to its maximum
  each turn.
- Make use of an Item. Some enemies will drop special items which can heal
  your Sinners, change status effects, or even deal elemental damage, but all
  of these are one-time-use only.
- Brace for attacks by Guarding. When you are Guarding, you will take a
  maximum of 1 damage for the entire turn, and cannot be stunned. If every
  Sinner is Guarding, all damage is prevented.
- Declare an intent to use Fusion. Fusion requires the cooperation of another
  Sinner, and is very powerful. See the chapter on Progression for more
  details.

As you act, other Abilities may trigger--your allies may have passive
Abilities that are related to your action, or an enemy may have an Ability
that affects how your Ability will work. You may even have a passive Ability
that triggers when you use one of your active Abilities. If this is the case,
your active Ability is 'paused' until the passive Ability resolves--that is,
*if a passive Ability is triggered, it resolves before the thing that
triggered it*. If two passive Abilities trigger at once, then Abilities
belonging to Sinners resolve first (in the order of the Sinners' choosing),
followed by abilities belonging to Demons. 
*** Damage and Stuns
When you cause damage to a Demon, there are two things to keep in mind: how
much damage was dealt, and what kind of damage it was.
Each Demon has a Weakness to one of the five elements. If that Demon takes
damage of that elemental type, that Demon is [Stunned]. It won't be able to
act until it is struck with a type of damage that does not match its
elemental type. Note that even attacks that deal 0 damage cause this to
happen! A zero-damage attack can be useful as a cheap way to Stun a target.
When a Demon is Stunned, you will gain one point of Meter.
You, too, can be Stunned. However, unlike the Demons, a Sinner will lose the
Stun effect after one turn.
If a Demon takes a certain amount of damage, it will be destroyed; naturally,
it won't be able to act, or be targeted by Abilities. When a Demon is
destroyed, you will gain one point of Meter.
If a Sinner is reduced to 0 HP, they are knocked unconscious. Abilities or
items that heal them will increase their HP, but they will remain unconscious
until they return to their maximum HP.An unconscious Sinner cannot do
anything.
Both Sinners and Demons who are stunned take double damage from all sources.
*** Breakdowns
When all Demons in the current Verse are stunned, a [Breakdown] automatically
occurs. During a Breakdown, all Sinners charge forth and deliver an
incredibly large can of whoop-ass to the helpless Demons before them. A
Breakdown causes all Demons (save for the most powerful among them) to be
destroyed.

*** Victory
When all Demons in a Verse are destroyed, the next Verse starts. The GM
decides how many Verses must be completed before total victory is achieved.
Upon finishing the final Verse, the party gains items based on how many party
members were fighting and how much Meter was left at the end; in short, the
fewer Sinners you bring to the fight, and the more Meter you have, the more
items you will get. If you end the battle with no Meter, you instead get a
single 'Link Shard'. Upon gathering 4 Link Shards, all Sinners present gain a
single Link Point.
** Progression
*** Link Points
As you make your way through the labyrinthine worlds of the Sinners' Souls,
you will gain [Link Points]. Link Points, or LP, represent the camearaderie
that you and your friends build up as you battle each others' Demons.
At any time outside of a Soul, or while inside a Soul at a 'Safe Room', you
may declare that you are spending a Link Point on another player character or
NPC. The other character may choose to spend a Link Point on you. If they do
so, you will establish a Link with them (if you already had a Link, it
becomes a Max Link).
Links do multiple things.
- Firstly, an NPC you have a Link with will follow your orders, assuming you
  don't order them to their deaths.
- Secondly, you will gain an additional point of Meter if you and a character
  you have a Link with attack the same target with an Ability or Basic
  Attack.
- Most importantly, Links count toward your next Ability.
*** New Abilities
During the course of your adventure, each Sinner will grow as a person, and will gain new powers.
Your character starts at Social Rank 1. For each new Link you gain, you add to your Social Rank.
You will gain new abilities at Social Ranks 2, 3, 5, and 8. Beyond that, refer to your GM; he may decide that you're capped at six abilities, or that you may gain additional ones.
When gaining a new Ability, bear these things in mind:
- Abilities that work with each other are useful. If you have an ability that causes enemies to gain some form of token, you may want your new ability to interact with that token in some way.
- If you already have several abilities that cost only a couple of points of Meter, you may want to gain an ability that costs more but hits harder. Similarly, if you've got several abilities that require large Meter usage, you may want something that can be used early in the battle.
- Passive abilities can be very useful, and at later stages of the game your GM may allow you to take direct stat increases like bonus HP or damage. You will probably want one or two passives to complement your active abilities.
*** Fusion
You gain new abilities by forming new Links; however, you can also improve
old Links. When you spend a Link Point on a character you already have an
existing Link with, you create a 'Max Link', and gain the ability to use a
powerful [Fusion Attack].
Fusion Attacks are special in a number of ways; firstly, they require the
cooperation of another character. You cannot perform Fusion Attacks if the
character you need to Fuse with refuses to work with you. Your turn isn't
wasted if this happens; if you try to use a Fusion Attack and fail, you can
still take a regular action.
Secondly, you must sacrifice part of your Meter. While a regular Ability
merely 'taps' part of the Meter, a Fusion Attack is draining enough to cause
you to lose Meter on a more permanent basis, reducing the amount of Meter you
have for your next turn. Meter spent on Fusion doesn't come back, but you can
still earn more with well-planned attacks.
Finally, many Fusion Attacks scale with the amount of Meter that is spent on
them. If you risk more of your Meter, you will hit harder. Note that you
cannot spend Meter you do not have! If you have already tapped part of the
Meter, you may only spend up to the amount of untapped Meter you have left on
a Fusion Attack.
Fusion Attacks are unique to each character pair. Work with your GM to create
a Fusion Attack that fits your characters.
*** The 'Persona'
Upon meeting your Sinner's doppelganger and surviving the events that follow,
you will gain a power that represents the mask you wear in the face of life's
struggles: the Persona. Each Persona is a legendary figure, someone that the
Sinner would look up to. Upon gaining a Persona, your Sinner also gains two
things:
- They immediately gain an Ability. Unlike regular progression, this Ability
  is immediately gained, meaning that meeting your doppelganger can lead to
  gaining two Abilities in quick succession. However, you will at most gain
  an ability that would require two Links to gain normally.
- They also gain a 'Groove', a special power that activates when certain
  conditions are met. There are three kinds of Grooves: Attack-Groove,
  Defense-Groove, and Support-Groove.
  Attack-Groove triggers when you kill an enemy. You may immediately grant
  one ally an extra turn.
  Defense-Groove triggers when you Guard and receive damage without being
  reduced to 0 HP. You may take an extra turn in the next Mainbeat.
  Support-Groove triggers when one of your Passive abilities takes effect.
  You immediately gain 1 extra Meter.

** Weapons, Items, and Safe Rooms
*** Items
Throughout your travels, you may come across various objects of importance.
Items fall into three categories:
- Weapons, which are unique to each character, and affect their Basic Attack;
- Consumables, which are used once for a certain effect;
- and Materials, which can be combined to make Consumables.
**** Weapons
Weapons are fairly rare, and are often given out as rewards for special
quests or clever puzzle solving. They are not physical weapons--the world of
the soul is beyond physical, and buying a new sword or a better gun has no
effect on your fighting power. Rather, a weapon represents the ability to
meet challenges in a new way, thanks to some realization or the end of an
internal struggle. Your GM will help you make new weapons when you earn them.
Common things a Weapon can do is allow you to do elemental damage with your
basic attack, or forgo damage for a debuff. Like your abilities, the limit is
up to you and your GM.
**** Consumables
Consumables range from healing items to one-shot weapons or status-effect
removing medicines. Consumables are fairly rare, and you're more likely to
make some of your own than you are to find them.
A few common Consumables include:
- Molotov (1 Fire damage to all targets)
- Healing Bandage (1 Heal to one ally)
- Lightning Rod (1 Lightning damage to 1 target)
**** Materials
Materials come in five varieties: Plates, Rods, Orbs, Cones, and Chunks. Each
one drops from enemies weak to a different type of damage. Further, Materials
can come in different qualities. Consult your GM to find out what different
materials make.
- Plates drop from enemies that are weak to Fire.
- Orbs drop from enemies that are weak to Ice.
- Rods drop from enemies that are weak to Lightning.
- Cones drop from enemies that are weak to Nature.
- Chunks are dropped by enemies that are weak to Physical.

A few examples of different qualities of Materials:
- Low Quality: Wood, Stone, Glass
- Mid Quality: Neon, Metal, Meat
- High Quality: Gold, Plasma, Obsidian
 
*** Safe Rooms
In certain areas of the horrific mazes you travel through, the GM may inform
you that you 'feel relatively safe' in this area, or that there seem to be
fewer Demons. He may even outright tell you that the room you're in is a
[Safe Room].
In a Safe Room, you may switch your weapons and party members freely. While
in a Safe Room, you will not be attacked by Demons. Be wary of enemies that
may not be demonic in nature.

