* Status Effects
Sometimes, things aren't as simple as damage. Status Effects act like extra
Passive abilities, causing strange things to happen. A list of Status Effects
follows.

** Positive Effects
- Regenerate: The target gains 1 HP each time they use an Ability or Basic Attack.
- True Aim: Whenever the target uses an Ability, they deal 1
  additional Physical damage to their target.
- Power Swing: Whenever the target uses a Basic Attack, they deal 1
  additional Physical damage to their target.
- Unison: Target may use one 3-meter-or-less ability without spending meter.
- Endure: Target survives KO with 1 HP.
** Negative Effects
- Depressed: Any time the target taps Meter, they tap 1 additional point of
  Meter.
- Mirrored: Any time the target deals damage, he/she also deals the same
  damage to his/herself.
- Guard Break: If the target prevents damage with leftover meter, they are stunned.
- Half Time: The target may only act every other turn.
- Stunned: Target may not act.
** Strange Effects
- Offset: Target must take their turn on the Backbeat. They may only use
  abilities that trigger and activate on the same beat.
- Manic: Target may only use their Basic Attack. Their Basic Attack deals
  double damage.
- Bent (Element1 > Element2): Target treats Element 1 as Element 2, for
  purposes of dealing elemental damage or being stunned. For example, Bent
  (Fire>Ice) causes the target to treat Fire as Ice.
